name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip \
            openjdk-17-jdk \
            autoconf automake libtool pkg-config \
            zlib1g-dev libncurses5-dev \
            libncursesw5-dev cmake \
            libffi-dev libssl-dev

      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip
          pip install buildozer
          pip install "cython==0.29.37"

      - name: Install Android SDK tools
        run: |
          mkdir -p $HOME/.buildozer/android/platform/android-sdk
          export ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH

          mkdir -p $ANDROID_HOME/cmdline-tools
          cd /tmp

          wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -q commandlinetools-linux-11076708_latest.zip

          mkdir -p $ANDROID_HOME/cmdline-tools/latest
          mv cmdline-tools/* $ANDROID_HOME/cmdline-tools/latest/

          yes | sdkmanager --licenses || true

          sdkmanager \
            "platform-tools" \
            "platforms;android-35" \
            "build-tools;35.0.0"

      - name: Build APK
        env:
          ANDROID_HOME: /home/runner/.buildozer/android/platform/android-sdk
          ANDROID_SDK_ROOT: /home/runner/.buildozer/android/platform/android-sdk
        run: |
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/35.0.0:$PATH
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: calculator-apk
          path: bin/*.apk
          if-no-files-found: error￼Enter
